[workspace]
members = ["foamer-cli",
    "foamer-configurator",
    "foamer-firmware",
    "foamer-types",
    "defmtusb",
]
resolver = "3"

[workspace.package]
authors = ["Mary Strodl <mstrodl@csh.rit.edu>"]
description = "Wi-Fi powered remote controller for model trains!"
repository = "https://github.com/Mstrodl/foamer-firmware"
homepage = "https://foamer.mstrodl.com"

[profile.release]
debug = 2

#[profile.dev]
#opt-level = 1

[profile.wasm]
inherits = "release"
opt-level = "s"
