env_scripts = [
'''
#!@duckscript

profile_filename = get_env CARGO_MAKE_CARGO_PROFILE
if eq "${profile_filename}" "dev"
  profile_filename = set "debug"
end
set_env PROFILE_FILENAME "${profile_filename}"
'''
]
[env]
OUTPUT_DIR = "dist"

[tasks.create-dist-dir]
script = '''
#!@duckscript
mkdir "${OUTPUT_DIR}"
'''

[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = ["-h"] }

[tasks.objcopy]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = ["objcopy", "--features", "usb-logging", "--profile", "${CARGO_MAKE_CARGO_PROFILE}", "--", "-O", "ihex", "${OUTPUT_DIR}/${CARGO_MAKE_CRATE_NAME}-${PROFILE_FILENAME}.hex"]
dependencies = ["install-llvm-tools", "flip-link", "create-dist-dir"]

[tasks.elf]
script_runner = "@duckscript"
script = '''
cp "${CARGO_MAKE_CRATE_CUSTOM_TRIPLE_TARGET_DIRECTORY}/${PROFILE_FILENAME}/${CARGO_MAKE_CRATE_NAME}" "${OUTPUT_DIR}/${CARGO_MAKE_CRATE_NAME}-${PROFILE_FILENAME}.elf"
'''
dependencies = ["objcopy"]

[tasks.uf2]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "${OUTPUT_DIR}/${CARGO_MAKE_CRATE_NAME}-${PROFILE_FILENAME}.hex",
    "--output-path",
    "${OUTPUT_DIR}/${CARGO_MAKE_CRATE_NAME}-${PROFILE_FILENAME}.uf2",
    "--family",
    "rp2040",
]
dependencies = ["objcopy"]

[tasks.archive]
dependencies = ["elf", "uf2"]
